name: "I need help hacking Prodigy!"
description: "Get help with hacking Prodigy."
title: "[O] title"
assignees: []
body:

  - type: markdown
    attributes:
      value: "# [Please go to our discord server to get help hacking Prodigy, don't just open an issue here. Click this text to join our Discord.](https://dsc.gg/ProdigyPNP)"
      
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Please do NOT sumbit this as a GitHub Issue, instead join our Discord
      options:
        - label: |
            I have joined the Discord and gotten help.
          required: true
